# ------------------------------------------------
# PARTIE 1 : Deployment
# D√©finit comment d√©ployer l'image Docker de votre application Spring Boot.
# ------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: devops
  labels:
    app: spring-app
spec:
  replicas: 2 # Nombre de r√©plicas (pour la haute disponibilit√©)
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-container
        # üö® Remplacer par l'image que votre pipeline Jenkins va construire et pousser
        image: dhiaayadi/dhiaayadii:latest 
        ports:
        - containerPort: 8080 # Le port sur lequel votre application Spring √©coute
        env:
        # Configuration de la connexion √† la base de donn√©es (MySQL)
        - name: SPRING_DATASOURCE_URL
          # Utilise le nom du Service MySQL (mysql-service) comme h√¥te
          value: "jdbc:mysql://mysql-service:3306/workshop_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "app_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "app_password_secret" # Doit correspondre √† la valeur dans mysql-deployment.yaml
---
# ------------------------------------------------
# PARTIE 2 : Service (NodePort)
# Cr√©e un point d'acc√®s externe pour l'application.
# ------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
  labels:
    app: spring-app
spec:
  ports:
    - port: 80 # Port standard pour l'acc√®s
      targetPort: 8080 # Port du conteneur Spring Boot
      # nodePort: 30000-32767 # Minikube assignera un NodePort dans cette plage
  selector:
    app: spring-app # Cible les Pods avec le label app: spring-app
  type: NodePort # Expose le service sur un port de la machine h√¥te (via minikube service)
