apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  namespace: devops
  labels:
    app: student
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student-app-container
        image: dhiaayadi/student:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/db_student
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
