apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: devops
  labels:
    app: student
spec:
  type: NodePort
  selector:
    app: student
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
